server:
  port: 9000
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    enable-self-preservation: false
  instance:
    hostname: 10.16.35.146
spring:
  application:
    name: pt-auth